apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-kust-2
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-kust-2
  template:
    metadata:
      labels:
        app: guestbook-kust-2
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-kust-2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-kust-2
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-kust-2
